### ISSUE TITLE
Ability to maintain what meta data items and content appear in the component info panel

### ISSUE THREAD

**Issue by pete-hotchkiss** [frctl/fractal#114]
For component documentation that's in constant development might be useful to be able to include component status and the accompanying description in the info panel.

Therefore the an ability to inject custom content into that panel would be usefull

**Comment by allmarkedup** [comment]
Hey @pete-hotchkiss - thanks yes that is definitely a good idea. The next point-release (v1.1) will be focussed around extensibility, both in the core and the default theme, so that hopefully stuff like this will be simple to add in to individual projects.

That said - I think that status description is something that should be in there by default so will add that into the next minor theme version release.
