### ISSUE TITLE
ISSUE: local preview layout rendering not working

### ISSUE THREAD

**Issue by pete-hotchkiss** [frctl/fractal#124]
I've got a _global_ preview defined in my fractal.js file
```javascript 
fractal.components.set('default.preview', '@preview');
```
All good there - renders nicely. However if I try and over ride that further down my component cascade, I don't seem to be able to use a local level template to render elements into at a component level.

In Pseudo folder set up I've got something like
```
├── components
│   ├── modals
│   │   ├── default.config.yml
│   │   ├── default.hbs
│   │   ├── _template.hbs
│   │   └── README.md
```
With ```_template.hbs``` being the file I want to use as the template override.

In the local ```default.config.yml``` file I'm also setting the preview like so

```
collated: true
status: prototype
label: Modal's Rock Kasbah 
preview: '@template'
variants:
```

Yet the compiler trips out and cant find the template 

![image](https://cloud.githubusercontent.com/assets/16895748/17700542/19e11eaa-63be-11e6-9818-fd5e30b89454.png)

Something I'm doing wrong ?

**Comment by pete-hotchkiss** [comment]
strike this issue, me not configuring the location of files correctly

**Comment by allmarkedup** [comment]
@pete-hotchkiss ok cool, basically at the moment a preview layout has to be a component in itself, so including within a component's directory won't work (because it will be seen as an asset instead). However I actually think that being able to add a specially named layout file (in the same way as the readme/config files work) would be very useful.

I'm going to open a separate issue as a feature request for this to track it.
