### ISSUE TITLE
How to reference a sub-folder of elements in a component folder?

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#162]
Hi

I know I can create variations of an element like this:
- form.hbs
- form--errors.hbs
- form--basic.hbs

However, each of these forms uses the same elements. Things like `name` and `email address` etc.

Ideally, I'd like to have a sub-folder inside my `form` component folder containing all the individual elements of my forms.

Is this possible? If it is, how do I reference them?

**Comment by allmarkedup** [comment]
@StephenMeehan2016 Fractal currently doesn't let you have sub-components nested within your component folders I'm afraid. Only collections can contain components. In your example you'd have to add a seperate 'fields' collection with your fields in, that you could then reference in your form components.

To be honest when I was building out the logic behind the directory parser I couldn't really find a compelling use-case for it. However since then examples (such as you one) have started to sway me towards some sort of sub-component nesting support so I'll add it into the list of feature requests and see if I can figure a way to implement it in a backwards compatible way at some point.
