### ISSUE TITLE
Build not copying additional static asset directories

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#200]
Seems that when adding additional static asset directories via:

```js
theme.addStatic('path/to/dir', '/my-assets');
```

...the assets are not being copied across when the build gets run.

**Comment by dkhuntrods** [comment]
Right, I've just tested this on a fresh install (Version 1.0.11) and all seems well.

I've this in `fractal.js`:

```
const myCustomisedTheme = mandelbrot();

myCustomisedTheme.addStatic( __dirname + '/foo', '/bar' );  

fractal.web.theme(myCustomisedTheme);
```
and the build destination is set like so:
```
fractal.web.set('builder.dest', path.join(__dirname, 'build'));
```

`/foo` contains a simple `sample.txt` file.

After running `fractal build` I see:

![screen shot 2017-01-09 at 16 43 18](https://cloud.githubusercontent.com/assets/852397/21774680/2128f06c-d68b-11e6-8cb9-d1a5adaab9f8.png)

`build/bar/sample.txt` as expected.

So, I tried a few different locations and file types in case it related to that, but all worked as expected. 

Any more info on the issue?

**Comment by dsingleton** [comment]
Hi @dkhuntrods, 

I reported this on Slack to @allmarkedup. We've been seeing it on this repo: https://github.com/alphagov/govuk_frontend_alpha. It's a fairly complex setup, which I suspect is part of the problem.

Our fractal config is here https://github.com/alphagov/govuk_frontend_alpha/blob/master/lib/fractal/config/fractal.js#L55, and our theme is defined here: https://github.com/alphagov/govuk_frontend_alpha/blob/master/lib/fractal/govuk-theme/index.js.

I've got a short-term fix PR on our repo (https://github.com/alphagov/govuk_frontend_alpha/pull/114/files), which illustrates the behaviour we'd like. As i mentioned on Slack earlier, i'm not 100% convinced it's a bug, it could be misunderstanding on my part.

**Comment by dkhuntrods** [comment]
Thanks @dsingleton, I'll take a look at those.

**Comment by dkhuntrods** [comment]
So, @dsingleton, I've replicated your setup, and I think we've tracked it down. 

Essentially, the `theme` directory that is output in the build step is created by the Mandlebrot theme and it was originally intended only for its use. Because the copy step is parallel, there's an IO conflict if you try to write to that directory whilst Mandlebrot is also writing to it. You can see this if you change the directory mount value to `theme/govuk` for instance: there's no issue.

To fix this right away, and incidentally avoid accidentally overwriting files that Mandlebrot uses, write to a different directory such as `themes/govuk` or something similar, so long as its not writing directly to the parent `theme` directory. 

Additionally, we're going to change Mandlebrot's output directory to `themes/mandlebrot`, to make such conflicts less likely in the future.

**Comment by dkhuntrods** [comment]
@dsingleton Any objections if we close this issue on /fractal? It'll still be open in /mandelbrot until the new build is released should you need to reference it.

**Comment by dsingleton** [comment]
@dkhuntrods none at all. Thanks for the help, and feel free to close :)
