### ISSUE TITLE
Sourcemaps: No matching route found

### ISSUE THREAD

**Issue by greaveselliott** [frctl/fractal#307]
I'm having some trouble viewing the sourcemaps for my SASS files. I'm presuming this is due to the preprocessed SASS files existing within the component directory, instead of the public directory. Is there a way I can include the component directory within Fractal's routing policies making them publicly available?

**Comment by ryanhagerty** [comment]
Hey, saw this and thought maybe I could help since I have sourcemaps working correctly.

I utilize a gulp file to process my Sass. Not sure how familiar you are with it or if you're using it, but here's my `styles` task. 

Here's my code for the `styles` task.

```gulp.task(`styles`, () => {
  return gulp.src(`src/assets/scss/*.scss`)
    .pipe(sourcemaps.init())
    .pipe(glob())
    .pipe(sass({
      includePaths: sassIncludes
    }))
    .pipe(autoprefixer())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(`build/assets/css`));
});```

There's other tasks in here that may or may not be pertinent to what you're doing, such as autoprefixer and a sassIncludes array, but this does the trick.

**Comment by macandcheese** [comment]
What do you mean when you say preprocessed @greaveselliott ? You'd want to set up a Gulp task to watch those component .scss files, and compile them to a css file Fractal can use for the  _preview view. 

As @ryanhagerty touches on, you'll need to do a little finagling if you want your component .scss files to reference a set of global variables, because even using imports won't allow for "ordered" concatenation. Further, if you want to be able to edit component-level .scss files and have them referenced in templates, you'll need to watch for changes and recompile the .css file _preview users.

I set up a seed Fractal project that supports component-level .scss compilation with a Gulp task, keeps a set of global variables the component .scss can depend on, and compiles to a public .css file you can reference in your _preview view: 

https://github.com/macandcheese/fractal-sass-seed

**Comment by dkhuntrods** [comment]
Hi @greaveselliott, basically that's down to how you handle your css processing task, so its not really part of Fractal. @macandcheese's solution is a good place to start.
In v2, we'll be adding some support for plugins to make this kind of thing easier for people that don't have a strong preference for their build approach.
