### ISSUE TITLE
is "components" a reserved directory name?

### ISSUE THREAD

**Issue by iamwebrocker** [frctl/fractal#353]
Hi,

I have this project structure (simplified):

```
fractal/
- components/...
- docs/....
dist/....
src/....
- scss/
 -- components/....
    _foo.scss
 -- setup/....
    _bar.scss
 styles.scss
....
```

I wondered why my ```gulp.watch( [pkg.directories.src  + '/scss/**/*.scss'], ['sass:dev']);``` watch didn't fire when a file in _scss/components/_ was changed, but a change in _scss/setup/_ was detected. as were changes in _scss/style.scss_.

After looking for clues in my gulp task, I changed "_scss/components_" to "_scss/modules_"
-- and now all changes are detected.

This makes me wonder if maybe the "components" directory name is somehow ignored for gulp tasks other than the fractal-internal stuff?

Maybe it wasn't the smartest idea to name my scss structure similar to the fractal structure, but I wouldn't have expected this effect :-)

Anyways, thanks for the great project, cheers,
Tom

**Comment by dkhuntrods** [comment]
Hi @iamwebrocker,
Fractal doesn't interface internally with gulp at all, so would have no awareness of anything in an `/scss` directory, I'm afraid (unless you've set your `src` as your public directory - which it looks like not, since you have a `dist` dir - and even then, it would not interfere with gulp). 

Might be worth having a look at the gulp setup, and confirming all paths & names are correct? 
Do you mind if I close this, as it can't really be directly Fractal related?

**Comment by iamwebrocker** [comment]
Hi @dkhuntrods,
thanks for looking into this. It was a mere guess from my side, b/c of the coincidence of those directory names (and that suddenly it worked when I changed the scss/components name), so no feelings are hurt when closing this :-)
