### ISSUE TITLE
Unable to npm uninstall @frctl/fractal -g

### ISSUE THREAD

**Issue by getsetbro** [frctl/fractal#423]
I installed @frctl/fractal globally and I am unable to uninstall it. I am able to uninstall other packages.

**Comment by colourgarden** [comment]
@getsetbro Please provide more information about what happens when you attempt to uninstall it. E.g. any error messages.

**Comment by getsetbro** [comment]
There is no error. It's just not gone after attempting to uninstall. Here is the log showing that I was able to remove 'lodash-cli' but then the attempt to uninstall '@frctl/fractal' failed:
https://gist.github.com/getsetbro/c770ff8ec05dd4d534ae731359206fab#file-npmuninstalllog-txt

BTW: What would the manual way of uninstalling be?

**Comment by colourgarden** [comment]
This is an npm issue rather than something to do with Fractal. There's an [old issue](https://github.com/npm/npm/issues/16738) which was fixed but seemingly not completely (see newer ticket references at bottom of thread).

To manually delete, navigate to the `/usr/local/lib` where your npm packages are being stored and manually delete the Fractal folder.
