### ISSUE TITLE
Set different preview layout for the builder

### ISSUE THREAD

**Issue by iKasch** [frctl/fractal#442]
Maybe there is a simple way to do this but something as simple as `fractal.components.set('builder.preview', '@anotherpreview');` isn't working.

Any other way to do this?

**Comment by iKasch** [comment]
Well, i tried it his way:

in my package.json i have the following scripts:

``` JSON
"start": "ENV=local fractal start --sync --watch",
"build": "ENV=build fractal build"
```

And in fractal.js:

``` JS
var env = process.env.ENV
// Set the preview layout
if (env == 'build') {
  fractal.components.set('default.preview', '@build');
} else {
  fractal.components.set('default.preview', '@preview'); 
}
```

This works .. except it ignores the `_build.hbs` file and will always use the `_preview.hbs`. Even if i just set it without the if and everything like `fractal.components.set('default.preview', '@build');` it will always use the `_preview.hbs`.

Bug? 
Ideas?

**Comment by iKasch** [comment]
Ok, i solved it. 

``` js
// Set the preview layout
if (env == 'build') {
  fractal.components.set('default.preview', '@aemexport');
  fractal.components.set('files.preview', '@build');
  console.log('We are using the following preview layout: ' + fractal.components._config.default.preview);
} else {
  fractal.components.set('default.preview', '@preview'); 
  console.log('We are using the following preview layout: ' + fractal.components._config.default.preview);
}
```

The important part is `fractal.components.set('files.preview', '@build');` The Docs only mention `default.preview` but not `files.preview`. I'm not sure it this is a bug or if the Docs are wrong but this works for now.

✌️

**Comment by mirkopoloni** [comment]
Hello everybody, I know it is an old (and closed) ticket but I had the same problem and I'm also wondering if I missed something about the `fractal.components.set('files.preview', '@build');` part.

I can't find it in the documentation but the default preview file won't work if we do not add the extra line of code.
Should the docs be updated?

**Comment by mihkeleidast** [comment]
I'd say it's more of a bug, the extra line should not be necessary.

**Comment by mihkeleidast** [comment]
I investigated this a bit. Working as expected in my testing.

The `files.preview` setting is used to look up a default preview file for a directory - e.g. if you have a `preview.hbs` in your `src/components/collection` folder, that preview file is automatically used for components in that collection. So this issue seems to happen only with some specific file structure that I haven't been able to replicate. Essentially if you have a preview template file in a collection directory, that preview is used instead of the default preview. If anyone running into this can provide a repository with this issue present, it would be great.

Either way, I'd like to know what the usecase is for using different preview templates serving/building and if maybe this would be better solved by conditional statements in a single preview template.

Closing this again, feel free to comment if any new info pops up and I can revisit this issue.
