### ISSUE TITLE
Custom template engine for Marko.js

### ISSUE THREAD

**Issue by taurni** [frctl/fractal#45]
I tried to write a custom template engine for marko.js, but can't get it to work. fractal had trouble to finding the module.
My custom adapter: https://github.com/taurni/marko-adapter
and demo project: https://github.com/taurni/fractal-demo
can you help me out?

**Comment by allmarkedup** [comment]
Hey @taurni - I don't know much about Marko specifically but I've noticed that there are a couple of typos in your adapter.js file - `moduel.exports` instead of `module.exports` ([on line 3](https://github.com/taurni/marko-adapter/blob/master/adapter.js#L3)) and `MArko` instead of `Marko` on [line 21](https://github.com/taurni/marko-adapter/blob/master/adapter.js#L21).

The first one will definitely cause an issue when trying to load the module. If you want to correct that and see if it works then I'll see if I can have a look at the best way to load and render templates based on Marko's API.

**Comment by taurni** [comment]
Hi. Thank you for pointing that out. I fixed some typos and now module loading works.
I took the [mustache-adapder](https://github.com/frctl/mustache-adapter/blob/master/adapter.js) as an example can you explane this a little bit? Is it the loadViews() function Mustache sptcific? I got TypeError: source.flattenDeep is not a function

**Comment by allmarkedup** [comment]
@taurni ok great - that loadViews function is really only needed for Handlebars as it expects you to pre-load all the partials. Marko (from what I can tell) works differently and just loads templates directly from the filesystem. So something like this should work for the adapter:

```js
'use strict';

const Marko = require('marko');

module.exports = function(source, config){

    return {
        engine: Marko,
        render: function(path, str, context, meta){
            const template = Marko.load(path, str, {writeToDisk: false});
            return new Promise(function(resolve,reject){
                template.render(context, function(err, html){
                    if(err !== null) return reject(err);
                    resolve(html);
                });
            });
        }
    }
};
```

You then need to make sure that you are configuring Fractal to use it in your fractal.js file - something like this:

```js
fractal.engine('marko', 'marko-adapter');
fractal.set('components.engine', 'marko');
fractal.set('components.ext', '.marko');
```

**Comment by allmarkedup** [comment]
@taurni let me know if that works! As I said I'm no Marko expert so it may need tweaking but something like the above should do the trick.

**Comment by allmarkedup** [comment]
@taurni I'm going to go ahead and close this issue now. Hopefully the above has given you what you need as a starting point.
