### ISSUE TITLE
Add Integration tests for v1

### ISSUE THREAD

**Issue by dkhuntrods** [frctl/fractal#457]
- [ ] Set up integration test framework (probably Cypress)
- [ ] Ensure Travis configured for:
  - [ ] OSX
  - [ ] Windows
  - [ ] Linux

- [ ] Add example projects:
  - [ ] (Default) handlebars
  - [ ] Nunjucks adapter
  - [ ] Twig adapter
  - ?

**Comment by Chapabu** [comment]
I've had some thought around this that would be good to discuss. 

* It's a given that we're going to need a basic Fractal setup fixture with the tests, so that's fine. 
* OOTB, we're only going to be able to test Handlebars, as we'll want to test the other adapters on their own. 
* We also need to ensure we test things both when running as a server, and as a compiled instance (if possible). Running reliable tests with a built in server is not as straightforward as you'd want it to be, si I think focusing on compiled tests is a better place to start. We can add server tests later.
* As a next step, it'd be good to perhaps provide some kind of _simple_ abstraction so we can make writing tests for adapters a really simple thing

**Comment by Chapabu** [comment]
Has any movement happened on this?

**Comment by mikkelrom** [comment]
Not from my side at least, been two busy :(
Would it make any sense to add UI tests and/or end-to-end tests? These are the tests I've done the most :)

**Comment by Chapabu** [comment]
The issue I see with UI/end-to-end tests, is that they'll _really_ be testing Mandlebrot for the most part. I mean...this is _useful_, but due to the nature of how Fractal is put together, I don't know:

1. Where these tests should go
2. Which repo these tests should be run against

Also, some other questions:

1. Do we expose some kind of helper system for testing other adapters (i.e. Nunjucks or Twig), or do we just test Handlebars as it's what we "ship" with.
2. Should we test the CLI processes? Like the build process?

**Comment by mihkeleidast** [comment]
I want to close this since I don't see this as being directly actionable anymore. #615 added the framework for integration testing (for the default Handlebars adapter).

If we want to add integration tests the other adapters, those could (& IMO should) be filed as separate actionable issues and resolved as such. If so, they should probably primarily focus on the specialties of the adapter (filters, helpers, tags, etc), not the core parsing of the file system, which is covered by the work in #615. 

If anyone thinks there are actionable items left in this issue, please list them out so we could all understand what's left to be done.
