### ISSUE TITLE
notes .md files not encoding numbers in an HTML entity correctly in a code example or block 

### ISSUE THREAD

**Issue by sturobson** [frctl/fractal#47]
if I add a note that needs to demo how to include a component, I will need to include something like

{{render @hoff-knight2000}}

However doing this alone renders the components code within the markdown file

If I put this in a code block it renders the components code in the codeblock

If I replace { with &123; and } with &125; this works unless it's in a codeblock or blockquote where the numbers don't rendered properly - which is pretty crappy.

**Comment by allmarkedup** [comment]
@sturobson So this happens because the notes.md files (like the rest of the documentation pages) are run through the Handlebars parser before being run through the markdown parser. That means that any Handlebars code needs to be escaped.

Handlebars supports this by ignoring handlebars expressions that start with a backslash escape character. So using  `\{{render @hoff-knight2000}}` should work to print out the statement as-is.

Can you give it a try and let me know if that works for you?

**Comment by sturobson** [comment]
Thanks @allmarkedup adding a backslash escape character before the first curly brace works a treat.
