### ISSUE TITLE
Time for a new npm release?

### ISSUE THREAD

**Issue by khawkins98** [frctl/fractal#471]
The last version/release published to npm was [on 19 Sep 2017](https://github.com/frctl/fractal/releases/tag/v1.1.7) and there have been quite a few changes, thoughts on publishing a 1.1.8?

Otherwise I'll have to `npm install --save frctl/fractal#master` 😓

**Comment by dkhuntrods** [comment]
Yep, planning on doing that in the next day or so actually. We're probably going to do a version pre-release though, to ensure that the updates won't break existing builds due to the extent of updates.

**Comment by dkhuntrods** [comment]
@khawkins98 thanks! 
We'll be announcing it more widely soon, but the new release is at `@stable.beta.1` tag. 
https://www.npmjs.com/package/@frctl/fractal/v/1.2.0-beta.1

**Comment by khawkins98** [comment]
Spied that in the commits. We're using and happy. 🤗

**Comment by dkhuntrods** [comment]
Fantastic!
It would be really helpful if, when you get a chance, you could send us
some details of your setup - OS, node+npm version, any adapters you're
using, and any customisations you've made.
Thank you!

**Comment by khawkins98** [comment]
Yep:
- Just updated to OS X 10.14 (`head` was also working fine on 10.13)
- `npm - v` 6.1.0
- `node -v` 10.5.0
- Using with gulp: CLI version 2.0.1;  Local version 4.0.0-alpha.3
- Using a custom frctl theme (why we needed nunjucks v3)

**Comment by dkhuntrods** [comment]
Brilliant, thank you

On 27 Sep 2018 10:50, "Ken Hawkins" <notifications@github.com> wrote:

Yep:

   - Just updated to OS X 10.14 (head was also working fine on 10.13)
   - npm - v 6.1.0
   - node -v 10.5.0
   - Using with gulp: CLI version 2.0.1; Local version 4.0.0-alpha.3
   - Using a custom frctl theme (why we needed nunjucks v3)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/frctl/fractal/issues/471#issuecomment-425030255>, or mute
the thread
