### ISSUE TITLE
Some text file formats are not displayed within the Assets panel

### ISSUE THREAD

**Issue by LeBenLeBen** [frctl/fractal#588]
### Expected behavior

Files using popular and recent file extensions such as .vue should be displayed in the "Assets" panel.

### Actual behavior

Fractal says it cannot parse/display these files.

### Steps to reproduce the issue

1. Add `resources` to the `panels` settings of Mandelbrot in your Fractal install
2. Add a .vue file in a component folder
3. Go to this component page, open the "Assets" panel
4. Select the .vue file in the dropdown

### Context

-   Fractal version: 
-   Node version: 12.14
-   OS: macOS 10.15.4

**Comment by risker** [comment]
This is generally fine, although we also have a TODO in code related to this: https://github.com/frctl/fractal/blob/master/src/core/fs.js#L13

Ideally I'd remove that completely, I don't get why we should allow extensions that are not in that public repo. Or, at least, remove extensions from there that are supported by that repo.

`istextorbinary` also supports promises via `isBinaryPromise` since 2.5.0 - i think we should upgrade to that instead of doing our own promisify.
