### ISSUE TITLE
Build static assets generates links beginning with /

### ISSUE THREAD

**Issue by igloosi** [frctl/fractal#59]
config:
`fractal.set('plugins.web.build.path', 'build');
fractal.set('components.path', 'components');
fractal.set('components.default.preview', '@preview');
fractal.set('plugins.web.static.path', 'public');
fractal.set('themes.mandelbrot.skin', 'orange');`

results at build: 

`<a class="Tree-entityLink" href="/components/detail/callout" data-pjax=""></a>`
resulting in unstyled page and broken links to components

dynamic serving works great

**Comment by allmarkedup** [comment]
Hi @igloosi - this is actually the expected behaviour. The output from the static build is intended to be served up using a web server and will not work when just opening the `.html` files up in a browser from your filesystem.

If you want to check that your static build has worked before deploying it to a server somewhere (and you have Python installed on your system), I find the `python -m SimpleHTTPServer` command useful to quickly serve up a directory at a localhost URL: http://www.2ality.com/2014/06/simple-http-server.html

**Comment by igloosi** [comment]
Hi @allmarkedup  - thanks for the info. I had mistaken a static build as a static / flat file. Something a .net developer/client would be able to open locally without running a server.

**Comment by allmarkedup** [comment]
@igloosi hmm ok - are you serving it from a subfolder? Like `http://localhost:8000/my-component-library/` or something like that?

**Comment by igloosi** [comment]
hi nope, from root. if i could join the slack channel we could figure it out there.

**Comment by allmarkedup** [comment]
Sure thing - can you let me know your email address? I haven't had time to automate the signup process yet :-)

**Comment by igloosi** [comment]
jani.kraner@gmail.com

**Comment by allmarkedup** [comment]
Hey @igloosi I've just sent you an invitation now :-) Sorry for the delay, busy today!

**Comment by igloosi** [comment]
thanks
