### ISSUE TITLE
Add created and last modified date into info panel

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#608]

**Comment by mihkeleidast** [comment]
If anyone has ideas on how to solve this, please say so - if I understand the original feature correctly, it would be necessary to save the component creation time somehow. Since Fractal only operates on static files, it's kind of impossible as far as I know. I guess it would maybe be possible to get the time from Git history, but I wouldn't want to make Fractal dependent on Git.

The only "proper" way for Fractal's static nature would be to add it as a static config property that users would need to fill out and update manually, but I'm not sure what the usefulness of said manual feature would be. I'd personally close this issue since it's not too clear what the benefit would be.
