### ISSUE TITLE
Fractal --watch refreshes the browser before SCSS compilation is complete

### ISSUE THREAD

**Issue by dzwarg** [frctl/fractal#634]
### Steps to reproduce the issue

1. Given a fractal project with component markup and SCSS (17 modules)
2. Start fractal with --watch
3. Navigate to a component **preview** page
4. Make a change to the component markup, and save it
5. The page refreshes with the markup  👍 
6. Make a change to the component SCSS, and save it
7. The page refreshes before the SCSS is fully compiled (and the `17 modules` message is emitted on the console) - the refreshed page doesn't have updated SCSS 👎 
8. Wait for the `17 modules` message to be emitted to the console
9. Refresh the page manually, and observe compiled SCSS changes are present

**Reproduces how often:**

100% of the time

### Reduced test case

TBD

### Context

-   Fractal version: 1.2.1
-   Node version: 10.16.3
-   OS: Linux 3d0ce8df1f37 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 Linux

### Hypothesis

Changed source files are detected by the watch mechanism, and the HTML re-rendering completes first. The SCSS compilation takes some time, so the refresh mechanism is triggered before the compiled SCSS is written to disk.

**Comment by LeBenLeBen** [comment]
This seems related to #134 somehow.

I have the feeling BrowserSync reloads because it saw that the SCSS file changed, but it should rather watch and reload when the compiled CSS file has changed. Unfortunately I think this isn't really related to Fractal but would be more something to configure in BrowserSync based on your assets compilation workflow. There are tips on how to ignore files in #134 and [BrowserSync docs](https://www.browsersync.io/docs) might help you as well.

I can also recommend you to check out [this repo](https://github.com/liip/styleguide-starterkit) which is a ready-to-use setup of Fractal with webpack. It doesn't write assets on disk in development, which is faster and prevent issues like the one you have.

If you think something’s within Fractal core actually cause this issue or prevent you from working around it, please let us know with more details and we’ll investigate further.
