### ISSUE TITLE
CSS inside compound component not working

### ISSUE THREAD

**Issue by carlotrimarchi** [frctl/fractal#641]
Hello,
I'm trying to define and use CSS styles on a component basis, but I can't make them work.

As an example, I created a `colors` component:

```
colors/
  colors.css
  colors.njk
  colors.config.json
```

In my `fractal.config.js` I modified the `panels` property to display the static assets

`panels: ['html', 'view', 'context', 'resources', 'info', 'notes'`

So, in the web UI I can see the CSS file but its styles are not applied to the component.

I think there's something wrong in the way I'm including the CSS in the component template. Here's what I tried:

```
<link rel="stylesheet" href="./colors.css">
<link rel="stylesheet" href="colors.css">
<link rel="stylesheet" href="{{ colors.css }}">
```
None of these worked. I also tried using the `path` but I gues it doesn't work with Nunjucks template, unless I'm missing something there.

Thanks for your help

**Comment by LeBenLeBen** [comment]
@carlotrimarchi Indeed, your solution doesn’t work because assets are not exposed at this location. AFAIK Fractal doesn’t provide helper methods to get an asset URL from within the component template (@mihkeleidast ?).

We have [some of this logic in Mandelbrot](https://github.com/frctl/fractal/blob/main/packages/mandelbrot/src/filters.js#L42-L46) though, you could reuse to [create your own filters](https://github.com/frctl/fractal/tree/main/packages/nunjucks#customisation) to dynamically include assets in [a preview layout](https://fractal.build/guide/components/preview-layouts.html#creating-a-preview-layout).

Or you could basically hardcode paths to assets in template like you started doing. Format is `/components/raw/{componentName}/{assetName}.{assetExtension}`. For your example it should be `/components/raw/colors/colors.css`.
