### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by maban** [frctl/fractal#94]
There are a few vulnerabilities in Fractal's dependencies that can easily be fixed using Snyk (yep, shamless plug): https://snyk.io/test/github/frctl/fractal

Would love to know what you think about it if you have time to give it a go.

**Comment by allmarkedup** [comment]
@maban so Snyk looks awesome, love it.

But... as a package distributor (as opposed to an end user), and provided my dependencies are up to date, there is not much else I can do apart from to recommend Snyk to people who use Fractal as a dependency to patch any issues at their end. Is that correct? I can't ship the dependency patches with Fractal itself, I assume.

Am I understanding things correctly here? Apologies if I've gotten the wrong end of the stick here!

**Comment by beesman** [comment]
@allmarkedup this is an interesting one. We've just run Snyk against our Fractal & it found 9 vulnerabilities. Some of these are because of unpatched dependencies, e.g. https://www.npmjs.com/package/marked has a high severity XSS vulnerability, but others are because Fractal is using older versions of libraries e.g. `express@2.5.11`. Would it be helpful to open issues for these?

**Comment by ShaneHudson** [comment]
This is still an issue in 2018, the marked vulnerability still exists in the old version that fractal uses.
